FROM python:alpine
MAINTAINER xavfan
RUN apk update && apk add bash


#RUN apk add --update --no-cache mariadb-client-libs \
#	&& apk add --no-cache --virtual .build-deps \
#		mariadb-dev \
#		gcc \
#		musl-dev \
#	&& pip install mysqlclient \
#	&& apk del .build-deps

RUN pip3 install mysqlclient
RUN pip3 install paho-mqtt
COPY mqtt-db-logger.py /data/


EXPOSE 1883
WORKDIR  /data/
#ENTRYPOINT ["python mqtt-db-logger.py "]
