FROM python:alpine
MAINTAINER xavfan
RUN apk update && apk add bash


RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev

RUN pip3 install mysqlclient
RUN apk del build-deps
RUN pip3 install paho-mqtt

EXPOSE 1883
WORKDIR  /data/
#ENTRYPOINT ["python mqtt-db-logger.py "]
